# Generated by Django 4.1.5 on 2023-01-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentgrades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='id',
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='user_id',
            field=models.CharField(default=201810848, max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Student ID'),
            preserve_default=False,
        ),
    ]
