# Generated by Django 4.1.5 on 2023-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentgrades_id_studentgrades_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='cosc50',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='dcit21',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='dcit22',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='fitt1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='gned02',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='gned05',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='gned11',
            field=models.FloatField(null=True),
        ),
    ]
