# Generated by Django 4.1.5 on 2023-01-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprof_user_id_studentprof_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprof',
            name='user_emailadd',
        ),
        migrations.RemoveField(
            model_name='studentprof',
            name='user_password',
        ),
    ]
