# Generated by Django 4.1.5 on 2023-01-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentprof_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprof',
            old_name='user_yrandsec',
            new_name='yrandsec',
        ),
    ]
