# Generated by Django 4.1.5 on 2023-01-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_rename_yrandsec_studentprof_user_yrandsec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='user_id',
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
