# Generated by Django 4.1.5 on 2023-01-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_remove_studentgrades_user_id_studentgrades_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fy2ndsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gned01', models.FloatField(null=True)),
                ('gned06', models.FloatField(null=True)),
                ('gned12', models.FloatField(null=True)),
                ('gned03', models.FloatField(null=True)),
                ('itec50', models.FloatField(null=True)),
                ('dcit23', models.FloatField(null=True)),
                ('fitt2', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
