# Generated by Django 4.1.5 on 2023-01-07 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_fy2ndsem'),
    ]

    operations = [
        migrations.CreateModel(
            name='sy1stsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gned04', models.FloatField(null=True)),
                ('gned07', models.FloatField(null=True)),
                ('gned10', models.FloatField(null=True)),
                ('gned14', models.FloatField(null=True)),
                ('itec55', models.FloatField(null=True)),
                ('dcit24', models.FloatField(null=True)),
                ('dcit50', models.FloatField(null=True)),
                ('fitt3', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
