# Generated by Django 4.1.5 on 2023-01-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_sy1stsem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ty2ndsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gned09', models.FloatField(null=True)),
                ('itec95', models.FloatField(null=True)),
                ('itec101', models.FloatField(null=True)),
                ('itec106', models.FloatField(null=True)),
                ('itec100', models.FloatField(null=True)),
                ('itec105', models.FloatField(null=True)),
                ('itec200a', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ty1stsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itec80', models.FloatField(null=True)),
                ('itec85', models.FloatField(null=True)),
                ('itec90', models.FloatField(null=True)),
                ('insy55', models.FloatField(null=True)),
                ('dcit26', models.FloatField(null=True)),
                ('dcit60', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sysummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat2', models.FloatField(null=True)),
                ('itec75', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sy2ndsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gned08', models.FloatField(null=True)),
                ('dcit25', models.FloatField(null=True)),
                ('itec60', models.FloatField(null=True)),
                ('itec65', models.FloatField(null=True)),
                ('dcit55', models.FloatField(null=True)),
                ('itec70', models.FloatField(null=True)),
                ('fitt4', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fy1stsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcit65', models.FloatField(null=True)),
                ('itec111', models.FloatField(null=True)),
                ('itec116', models.FloatField(null=True)),
                ('itec110', models.FloatField(null=True)),
                ('itec200b', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fry2ndsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itec199', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
