# Generated by Django 4.1.5 on 2023-01-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ty2ndsem_ty1stsem_sysummer_sy2ndsem_fy1stsem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='nstp1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='ornt1',
            field=models.FloatField(null=True),
        ),
    ]
