# Generated by Django 4.1.5 on 2023-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_studentgrades_nstp1_studentgrades_ornt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprof',
            name='user_section',
            field=models.CharField(max_length=200, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='studentprof',
            name='user_yrandsec',
            field=models.CharField(max_length=200, verbose_name='Year'),
        ),
    ]
