# Generated by Django 4.1.5 on 2023-01-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_first_year_2ndsem_fy2ndsem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fy2ndsem',
            name='nstp2',
            field=models.FloatField(null=True),
        ),
    ]
