# Generated by Django 4.1.5 on 2023-01-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_adviserprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserprof',
            old_name='adviser_course',
            new_name='adviser_position',
        ),
        migrations.RemoveField(
            model_name='adviserprof',
            name='adviser_section',
        ),
        migrations.RemoveField(
            model_name='adviserprof',
            name='adviser_yrandsec',
        ),
    ]
