# Generated by Django 4.1.5 on 2023-01-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_alter_fry2ndsem_itec199_alter_fy1stsem_dcit65_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprof',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
