# Generated by Django 4.1.5 on 2023-01-17 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_alter_fry2ndsem_user_alter_fy1stsem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_cnumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_fname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_lname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_mname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='adviser_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='adviserprof',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
